-- home_banners — 홈메인 어드민 9개 섹션 (Supabase Dashboard → SQL Editor)
-- section_id당 1행 Upsert. metadata(jsonb)에 섹션별 상세 설정(다중 슬라이드·텍스트 등) 저장.

CREATE TABLE IF NOT EXISTS public.home_banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id text NOT NULL,
  image_url text,
  link_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.home_banners ADD COLUMN IF NOT EXISTS section_id text;
ALTER TABLE public.home_banners ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.home_banners ADD COLUMN IF NOT EXISTS link_url text;
ALTER TABLE public.home_banners ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.home_banners ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- image_url / link_url: optional denormalized fields; full config lives in metadata (jsonb).
-- Quick menu, curation, etc. may save text-only before any image is uploaded.
ALTER TABLE public.home_banners ALTER COLUMN image_url DROP NOT NULL;
ALTER TABLE public.home_banners ALTER COLUMN link_url DROP NOT NULL;

-- section_id unique (Upsert 키)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'home_banners_section_id_key'
      AND conrelid = 'public.home_banners'::regclass
  ) THEN
    ALTER TABLE public.home_banners ADD CONSTRAINT home_banners_section_id_key UNIQUE (section_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS home_banners_section_id_idx ON public.home_banners (section_id);

-- ── RLS: 누구나 읽기 / 어드민(anon) 쓰기 ─────────────────────────────────────
ALTER TABLE public.home_banners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "home_banners_select_public" ON public.home_banners;
CREATE POLICY "home_banners_select_public"
ON public.home_banners FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "home_banners_insert_anon" ON public.home_banners;
CREATE POLICY "home_banners_insert_anon"
ON public.home_banners FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "home_banners_update_anon" ON public.home_banners;
CREATE POLICY "home_banners_update_anon"
ON public.home_banners FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "home_banners_delete_anon" ON public.home_banners;
CREATE POLICY "home_banners_delete_anon"
ON public.home_banners FOR DELETE
TO anon, authenticated
USING (true);
